Simplify capabilities (Task #4194)
QoboLtd/cakephp-roles-capabilities pull request #160
Opened 2020-11-25 14:52 UTC by nicosp

Major change.

- Converts the plugin from an event listener to per-table behavior.
- A SubjectInterface is introduced to clearly define the contract between application and plugin.
- Middleware for easiy integration to authentication middleware.
- Entity-based Authorization adapter for AuthComponent (optional).

2020-11-25 15:16 UTC, softius requested changes

2020-11-25 15:16 UTC, softius commented on src/EntityAccess/AccessControlTrait.php
> +    public function isActionAuthorized(Controller $controller, string $action, ?string $entityId, ?SubjectInterface $user = null): bool
@nicosp shall we rename this to `isControllerActionAuthorized` ?

2020-11-25 15:16 UTC, softius commented on src/EntityAccess/CapabilitiesUtil.php
> +        foreach ($map as $class => $path) {
@nicosp there are a few app helpers that we could possibly use here like `App::shortName`

2020-11-25 15:16 UTC, softius commented on src/EntityAccess/CapabilitiesUtil.php
> +        if ($table->hasBehavior('Authorized')) {
@nicosp one more return early.

2020-11-25 15:16 UTC, softius commented on src/EntityAccess/CapabilitiesUtil.php
> +        if ($table->hasBehavior('Authorized')) {
@nicosp same here.

2020-11-25 15:16 UTC, softius commented on src/EntityAccess/EntityCapabilityRule.php
> +    private function aliasTable(): string
@nicosp lets explain why we needed this for future reference.

2020-11-25 15:16 UTC, softius commented on src/EntityAccess/EntityCapabilityRule.php
> +            ->applyOptions(['filterQuery' => true ])
@nicosp something is off with the spacing here.

2020-11-25 15:16 UTC, softius commented on src/EntityAccess/Event/ModelInitializeListener.php
> +        if ($config !== null) {
@nicosp perhaps you can add a return in above `if` and remove the extra if here.

2020-11-25 15:53 UTC, nicosp commented on src/EntityAccess/AccessControlTrait.php
> +    public function isActionAuthorized(Controller $controller, string $action, ?string $entityId, ?SubjectInterface $user = null): bool
Done

2020-11-25 15:53 UTC, nicosp commented on src/EntityAccess/CapabilitiesUtil.php
> +        if ($table->hasBehavior('Authorized')) {
Done

2020-11-25 15:53 UTC, nicosp commented on src/EntityAccess/EntityCapabilityRule.php
> +    private function aliasTable(): string
Done

2020-11-25 15:53 UTC, nicosp commented on src/EntityAccess/Event/ModelInitializeListener.php
> +        if ($config !== null) {
Done

2020-11-25 16:02 UTC, nicosp commented on src/EntityAccess/CapabilitiesUtil.php
> +        foreach ($map as $class => $path) {
Done

2020-11-26 08:26 UTC, softius requested changes

2020-11-26 08:26 UTC, softius commented on src/EntityAccess/EntityCapabilityRule.php
> +        $isEmpty = true;
@nicosp i dont follow why we need `$isEmpty` here can you please advise and perhaps add a comment?

2021-01-22 10:10 UTC, softius approved these changes

2022-03-15 14:18 UTC, closed without merging